###############################################################################
#                          Generated on phpdocker.io                          #
#
# Generic instructions: docker-compose up -d
#
# webDiplomacy instructions:
# Copy config.sample.php to config.php
# Run install/FullInstall/FullInstall.sql
# Register user account, use https://localhost:43001 to access registration mail
# Go to https://localhost:43000/gamemaster.php?gameMasterSecret= to set self as admin
# Go to https://localhost:43000/admincp.php and enable maintenance mode
# Go to https://localhost:43000/datc.php and run batch test
# Go to https://localhost:43000/admincp.php and disable maintenance mode
# Server is ready for dev work
#
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '43001:8025'

    mariadb:
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - './:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=mypassword123
            - MYSQL_DATABASE=webdiplomacy
            - MYSQL_USER=webdiplomacy
            - MYSQL_PASSWORD=mypassword123
        ports:
            - '43003:3306'

    clickhouse:
        image: 'yandex/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '43000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
